apiVersion: apps/v1
kind: Deployment
metadata:
  name: postiz
  namespace: postiz

spec:
  replicas: 3

  selector:
    matchLabels:
      app: postiz

  template:
    metadata:
      labels:
        app: postiz

    spec:
      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80
