apiVersion: apps/v1
kind: Deployment

metadata:
  name: postiz
  namespace: postiz

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postiz

  template:
    metadata:
      labels:
        app: postiz

    spec:
      containers:
      - name: postiz

        image: ghcr.io/gitroomhq/postiz-app:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: postiz-config
              key: REDIS_HOST

        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: postiz-config
              key: REDIS_PORT

        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: postiz-config
              key: DATABASE_HOST

        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: postiz-config
              key: DATABASE_PORT

        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: postiz-config
              key: DATABASE_NAME

        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postiz-secret
              key: DATABASE_USER

        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postiz-secret
              key: DATABASE_PASSWORD

        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postiz-secret
              key: DATABASE_URL

        resources:
          requests:
            cpu: 200m
            memory: 512Mi

          limits:
            cpu: 1000m
            memory: 2Gi
