apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postiz

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
      - name: postgres
        image: postgres:16

        env:
        - name: POSTGRES_DB
          value: postiz

        - name: POSTGRES_USER
          value: postiz

        - name: POSTGRES_PASSWORD
          value: postiz123

        ports:
        - containerPort: 5432
