apiVersion: v1
kind: Secret
metadata:
  name: postiz-secret
  namespace: postiz

type: Opaque

stringData:
  DATABASE_USER: postiz
  DATABASE_PASSWORD: postiz123
  DATABASE_URL: postgresql://postiz:postiz123@postgres-service:5432/postiz
